name: CI

on:
  pull_request:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JSONRS_BUILD: true
  CARGO_INCREMENTAL: 0

permissions:
  contents: read

jobs:
  test:

    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.17
              otp: 26
          - pair:
              elixir: 1.17
              otp: 27

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.pair.elixir}}
        otp-version: ${{matrix.pair.otp}}
    - name: Restore Elixir dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-
    - name: Restore Cargo cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test

